//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeRecipes
    {
        public int id { get; set; }
        public int idAuthor { get; set; }
        public int idRecipes { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
